version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      java: openjdk8

    commands:
      - sbt --version
      - sdk install sbt

  pre_build:
    commands:
      - echo Start Building Feature Store Spark Library...
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging pyspark library according to the instructions in setup.py...
      - cd pyspark-sdk
      - python setup.py sdist
      - echo Packaging finished, start running integration test
      - cd integration_test
      - ./run-spark-integration-test
  post_build:
    commands:
      - echo Build completed on `date`